const keysEn = [
  { mainKey: '`', subKey: '¬', code: 'Backquote' },
  { mainKey: '1', subKey: '!', code: 'Digit1' },
  { mainKey: '2', subKey: '"', code: 'Digit2' },
  { mainKey: '3', subKey: '£', code: 'Digit3' },
  { mainKey: '4', subKey: '$', code: 'Digit4' },
  { mainKey: '5', subKey: '%', code: 'Digit5' },
  { mainKey: '6', subKey: '^', code: 'Digit6' },
  { mainKey: '7', subKey: '&', code: 'Digit7' },
  { mainKey: '8', subKey: '*', code: 'Digit8' },
  { mainKey: '9', subKey: '(', code: 'Digit9' },
  { mainKey: '0', subKey: ')', code: 'Digit0' },
  { mainKey: '-', subKey: '_', code: 'Minus' },
  { mainKey: '=', subKey: '+', code: 'Equal' },
  { mainKey: 'Backspace', code: 'Backspace', width: '170px' },
  { mainKey: 'Tab', code: 'Tab', width: '80px' },
  { mainKey: 'q', code: 'KeyQ' },
  { mainKey: 'w', code: 'KeyW' },
  { mainKey: 'e', code: 'KeyE' },
  { mainKey: 'r', code: 'KeyR' },
  { mainKey: 't', code: 'KeyT' },
  { mainKey: 'y', code: 'KeyY' },
  { mainKey: 'u', code: 'KeyU' },
  { mainKey: 'i', code: 'KeyI' },
  { mainKey: 'o', code: 'KeyO' },
  { mainKey: 'p', code: 'KeyP' },
  { mainKey: '[', subKey: '{', code: 'BracketLeft' },
  { mainKey: ']', subKey: '}', code: 'BracketRight' },
  { mainKey: '~', code: 'BacksLash' },
  { mainKey: 'Del', code: 'Delete', width: '80px' },
  { mainKey: 'Caps Lock', code: 'CapsLock', width: '140px' },
  { mainKey: 'a', code: 'KeyA' },
  { mainKey: 's', code: 'KeyS' },
  { mainKey: 'd', code: 'KeyD' },
  { mainKey: 'f', code: 'KeyF' },
  { mainKey: 'g', code: 'KeyG' },
  { mainKey: 'h', code: 'KeyH' },
  { mainKey: 'j', code: 'KeyJ' },
  { mainKey: 'k', code: 'KeyK' },
  { mainKey: 'l', code: 'KeyL' },
  { mainKey: ';', subKey: ':', code: 'Semicolon' },
  { mainKey: '\'', subKey: '@', code: 'Quote' },
  { mainKey: 'Enter', code: 'Enter', width: '140px' },
  { mainKey: 'Shift', code: 'ShiftLeft', width: '140px' },
  { mainKey: 'z', code: 'KeyZ' },
  { mainKey: 'x', code: 'KeyX' },
  { mainKey: 'c', code: 'KeyC' },
  { mainKey: 'v', code: 'KeyV' },
  { mainKey: 'b', code: 'KeyB' },
  { mainKey: 'n', code: 'KeyN' },
  { mainKey: 'm', code: 'KeyM' },
  { mainKey: ',', subKey: '<', code: 'Comma' },
  { mainKey: '.', subKey: '>', code: 'Period' },
  { mainKey: '/', subKey: '?', code: 'Slash' },
  { mainKey: '↑', code: 'ArrowUp' },
  { mainKey: 'Shift', code: 'ShiftRight', width: '140px' },
  { mainKey: 'Ctrl', code: 'ControlLeft', width: '80px' },
  { mainKey: 'Win', code: 'MetaLeft', width: '80px' },
  { mainKey: 'Alt', code: 'AltLeft', width: '80px' },
  { mainKey: ' ', code: 'Space', width: '320px' },
  { mainKey: 'Alt', code: 'AltRight', width: '80px' },
  { mainKey: '←', code: 'ArrowLeft' },
  { mainKey: '↓', code: 'ArrowDown' },
  { mainKey: '→', code: 'ArrowRight' },
  { mainKey: 'Ctrl', code: 'ControlRight', width: '80px' },
];

export default keysEn;
