const keysBy = [
    { mainKey: 'ё', code: 'Backquote' },
    { mainKey: '1', subKey: '!', code: 'Digit1' },
    { mainKey: '2', subKey: '@', code: 'Digit2' },
    { mainKey: '3', subKey: '№', code: 'Digit3' },
    { mainKey: '4', subKey: ';', code: 'Digit4' },
    { mainKey: '5', subKey: '%', code: 'Digit5' },
    { mainKey: '6', subKey: ':', code: 'Digit6' },
    { mainKey: '7', subKey: '?', code: 'Digit7' },
    { mainKey: '8', subKey: '*', code: 'Digit8' },
    { mainKey: '9', subKey: '(', code: 'Digit9' },
    { mainKey: '0', subKey: ')', code: 'Digit0' },
    { mainKey: '-', subKey: '_', code: 'Minus' },
    { mainKey: '=', subKey: '+', code: 'Equal' },
    { mainKey: 'Backspace', code: 'Backspace' , width: '170px'},
    { mainKey: 'Tab', code: 'Tab' , width: '80px'},
    { mainKey: 'й', code: 'KeyQ' },
    { mainKey: 'ц', code: 'KeyW' },
    { mainKey: 'у', code: 'KeyE' },
    { mainKey: 'к', code: 'KeyR' },
    { mainKey: 'е', code: 'KeyT' },
    { mainKey: 'н', code: 'KeyY' },
    { mainKey: 'г', code: 'KeyU' },
    { mainKey: 'ш', code: 'KeyI' },
    { mainKey: 'ў', code: 'KeyO' },
    { mainKey: 'з', code: 'KeyP' },
    { mainKey: 'х', code: 'BracketLeft' },
    { mainKey: `'`, code: 'BracketRight' },
    { mainKey: '\\', subKey: '/', code: 'BacksLash' },
    { mainKey: 'Del', code: 'Delete' , width: '80px'},
    { mainKey: 'Caps Lock', code: 'CapsLock' , width: '140px'},
    { mainKey: 'ф', code: 'KeyA' },
    { mainKey: 'ы', code: 'KeyS' },
    { mainKey: 'в', code: 'KeyD' },
    { mainKey: 'а', code: 'KeyF' },
    { mainKey: 'п', code: 'KeyG' },
    { mainKey: 'р', code: 'KeyH' },
    { mainKey: 'о', code: 'KeyJ' },
    { mainKey: 'л', code: 'KeyK' },
    { mainKey: 'д', code: 'KeyL' },
    { mainKey: 'ж', code: 'Semicolon' },
    { mainKey: 'э', code: 'Quote' },
    { mainKey: 'Enter', code: 'Enter', width: '140px' },
    { mainKey: 'Shift', code: 'ShiftLeft' , width: '140px'},
    { mainKey: 'я', code: 'KeyZ' },
    { mainKey: 'ч', code: 'KeyX' },
    { mainKey: 'с', code: 'KeyC' },
    { mainKey: 'м', code: 'KeyV' },
    { mainKey: 'і', code: 'KeyB' },
    { mainKey: 'т', code: 'KeyN' },
    { mainKey: 'ь', code: 'KeyM' },
    { mainKey: 'б', code: 'Comma' },
    { mainKey: 'ю', code: 'Period' },
    { mainKey: '.', subKey: ',', code: 'Slash' },
    { mainKey: '↑', code: 'ArrowUp' },
    { mainKey: 'Shift', code: 'ShiftRight' , width: '140px'},
    { mainKey: 'Ctrl', code: 'ControlLeft' , width: '80px'},
    { mainKey: 'Win', code: 'MetaLeft' , width: '80px'},
    { mainKey: 'Alt', code: 'AltLeft' , width: '80px'},
    { mainKey: ' ', code: 'Space' , width: '320px'},
    { mainKey: 'Alt', code: 'AltRight', width: '80px' },
    { mainKey: '←', code: 'ArrowLeft' },
    { mainKey: '↓', code: 'ArrowDown' },
    { mainKey: '→', code: 'ArrowRight' },
    { mainKey: 'Ctrl', code: 'ControlRight' , width: '80px'},
]

export { keysBy };