const keysBy = [
    { mainKey: 'ё' },
    { mainKey: '1', subKey: '!' },
    { mainKey: '2', subKey: '@' },
    { mainKey: '3', subKey: '№' },
    { mainKey: '4', subKey: ';' },
    { mainKey: '5', subKey: '%' },
    { mainKey: '6', subKey: ':' },
    { mainKey: '7', subKey: '?' },
    { mainKey: '8', subKey: '*' },
    { mainKey: '9', subKey: '(' },
    { mainKey: '0', subKey: ')' },
    { mainKey: '-', subKey: '_' },
    { mainKey: '=', subKey: '+' },
    { mainKey: 'Backspace' },
    { mainKey: 'Tab' },
    { mainKey: 'й' },
    { mainKey: 'ц' },
    { mainKey: 'у' },
    { mainKey: 'к' },
    { mainKey: 'е' },
    { mainKey: 'н' },
    { mainKey: 'г' },
    { mainKey: 'ш' },
    { mainKey: 'ў' },
    { mainKey: 'з' },
    { mainKey: 'х' },
    { mainKey: `'` },
    { mainKey: '\\' , subKey: '/' },
    { mainKey: 'Del' },
    { mainKey: 'Caps Lock' },
    { mainKey: 'ф' },
    { mainKey: 'ы' },
    { mainKey: 'в' },
    { mainKey: 'а' },
    { mainKey: 'п' },
    { mainKey: 'р' },
    { mainKey: 'о' },
    { mainKey: 'л' },
    { mainKey: 'д' },
    { mainKey: 'ж' },
    { mainKey: 'э' },
    { mainKey: 'Enter' },
    { mainKey: 'Shift' },
    { mainKey: 'я' },
    { mainKey: 'ч' },
    { mainKey: 'с' },
    { mainKey: 'м' },
    { mainKey: 'і' },
    { mainKey: 'т' },
    { mainKey: 'ь' },
    { mainKey: 'б' },
    { mainKey: 'ю' },
    { mainKey: '.'  , subKey: ',' },
    { mainKey: '↑' },
    { mainKey: 'Shift' },
    { mainKey: 'Ctrl' },
    { mainKey: 'Win' },
    { mainKey: 'Alt' },
    { mainKey: 'Space' },
    { mainKey: 'Alt' },
    { mainKey: 'Ctrl' },
    { mainKey: '←' },
    { mainKey: '↓' },
    { mainKey: '→' },
]

export {keysBy};