const keysEn = [
    { mainKey: '`', subKey: '¬' },
    { mainKey: '1', subKey: '!' },
    { mainKey: '2', subKey: '"' },
    { mainKey: '3', subKey: '£' },
    { mainKey: '4', subKey: '$' },
    { mainKey: '5', subKey: '%' },
    { mainKey: '6', subKey: '^' },
    { mainKey: '7', subKey: '&' },
    { mainKey: '8', subKey: '*' },
    { mainKey: '9', subKey: '(' },
    { mainKey: '0', subKey: ')' },
    { mainKey: '-', subKey: '_' },
    { mainKey: '=', subKey: '+' },
    { mainKey: 'Backspace' },
    { mainKey: 'Tab' },
    { mainKey: 'q' },
    { mainKey: 'w' },
    { mainKey: 'e' },
    { mainKey: 'r' },
    { mainKey: 't' },
    { mainKey: 'y' },
    { mainKey: 'u' },
    { mainKey: 'i' },
    { mainKey: 'o' },
    { mainKey: 'p' },
    { mainKey: '[', subKey: '{' },
    { mainKey: `]`, subKey: '}' },
    { mainKey: '~' },
    { mainKey: 'Del' },
    { mainKey: 'Caps Lock' },
    { mainKey: 'a' },
    { mainKey: 's' },
    { mainKey: 'd' },
    { mainKey: 'f' },
    { mainKey: 'g' },
    { mainKey: 'h' },
    { mainKey: 'j' },
    { mainKey: 'k' },
    { mainKey: 'l' },
    { mainKey: ';', subKey: ':' },
    { mainKey: `'`, subKey: '@' },
    { mainKey: 'Enter' },
    { mainKey: 'Shift' },
    { mainKey: 'z' },
    { mainKey: 'x' },
    { mainKey: 'c' },
    { mainKey: 'v' },
    { mainKey: 'b' },
    { mainKey: 'n' },
    { mainKey: 'm' },
    { mainKey: ',', subKey: '<' },
    { mainKey: '.', subKey: '>' },
    { mainKey: '/'  , subKey: '?' },
    { mainKey: '↑' },
    { mainKey: 'Shift' },
    { mainKey: 'Ctrl' },
    { mainKey: 'Win' },
    { mainKey: 'Alt' },
    { mainKey: 'Space' },
    { mainKey: 'Alt' },
    { mainKey: 'Ctrl' },
    { mainKey: '←' },
    { mainKey: '↓' },
    { mainKey: '→' },
]


export { keysEn };